name: smartdolap
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.5
  intl: ^0.20.2
  lottie: ^3.1.2
  pdf: ^3.11.3
  printing: ^5.13.3
  share_plus: ^10.1.2
  shimmer: ^3.0.0
  timezone: ^0.9.4
  uuid: ^4.4.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.2
  mocktail: ^1.0.4
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - .env
    # - assets/animations/   # optional, if you add local lottie files later
